apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
spec:
  containers:
    - name: hello-world-container
      image: busybox
      command: ['sh', '-c', 'echo "Hello, World!" && sleep 3600']
